name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache: "poetry"

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install --no-root

    - name: Build package
      run: |
        poetry build
        ls -l dist

    - name: Upload artefacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  publish-to-pypi:
    name: >-
      Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/capywfa
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download dist
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
