# This workflow will install Python dependencies and run some static checks

# SPDX-FileCopyrightText: 2021-2025 Siemens
# SPDX-FileContributor: Thomas Graf <thomas.graf@siemens.com>
# SPDX-FileContributor: Gernot Hillier <gernot.hillier@siemens.com>
# SPDX-License-Identifier: MIT

name: Static Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache: "poetry"

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install --no-root

    - name: Lint with flake8
      run: |
        poetry run flake8 .

    - name: markdownlint
      uses: nosborn/github-action-markdown-cli@v3.3.0
      with:
        files: .
        config_file: .markdownlint.yaml
